/*

SALDOS EN PERIODO

USE MIDOKA_PGC_B;SELECT opID AS OPERACION,DENOMINACION,DEBE,HABER FROM CUENTA_CORRIENTE JOIN(OPERACIONES,CLIENTE) ON(opID=OPERACION_REF_CC AND INTERESADO=clID) WHERE COMPLETADO>="2019-06-01" AND COMPLETADO<="2019-06-15";

--------------------------------------------
SOLO COBROS EN PERIODO

USE MIDOKA_PGC_B;SELECT opID AS OPERACION,DENOMINACION,HABER FROM CUENTA_CORRIENTE JOIN(OPERACIONES,CLIENTE) ON(opID=OPERACION_REF_CC AND INTERESADO=clID) WHERE COMPLETADO>="2019-06-01" AND COMPLETADO<="2019-06-15" AND DEBE=0 AND HABER !=0 ORDER BY DENOMINACION;*/

--------------------------------------------

/*VENTAS SUMADAS EL DIA DE SU FACTURACION */

USE MIDOKA_PGC_B;SELECT SUM(DEBE) FROM CUENTA_CORRIENTE JOIN(OPERACIONES,CLIENTE,SOLICITUDES) ON(opID=OPERACION_REF_CC AND INTERESADO=clID AND REFERENCIA=opID) WHERE COMIENZO>="2019-06-01" AND COMIENZO<="2019-06-15" AND CLASE=9;
