USE MIDOKA_PGC_B;

SELECT t1.MES AS MES,
       t8.NETO AS NETO,
       ROUND(t1.COSTO, 2) AS 'COSTO MERCADERIAS',
       IFNULL(t2.PERDIDAS, 0) AS PERDIDAS,
       ROUND(t3.MONTO, 2) AS COMISIONES,
       IFNULL(t9.REGISTRO, 0) AS 'COMISIONES EXTRA',
       IFNULL(t4.REGISTRO, 0) AS 'FIJOS',
       IFNULL(t5.REGISTRO, 0) AS 'MOVILIDAD',
       IFNULL(t6.REGISTRO, 0) AS 'INSUMOS',
       ROUND(t7.INGRESO_PABLO, 2) AS 'INGRESOS PABLO'
FROM
  (SELECT DATE_FORMAT(SOLICITUDES.COMIENZO, '%Y-%m') AS MES,
          SUM((CANTIDAD_AR-IF(OPERACIONES.SOLICITUD=42, CANTIDAD_ING, 0))*CANTIDAD_MINIMA*t1.PRECIO*(1 - IFNULL(DESCUENTO, 0) / 100)) AS 'COSTO'
   FROM ARMADO JOIN(PRECIOS, CATEGORIA, MODELO, CONDICION, ARTICULOS, CLIENTE, OPERACIONES, PROOVEDOR, SOLICITUDES) ON(PRECIOS.RUBRO_pr=ARTICULOS.RUBRO
                                                                                                          AND PRECIOS.CATEGORIA_pr=ARTICULOS.CATEGORIA
                                                                                                          AND PRECIOS.MODELO_pr=ARTICULOS.MODELO
                                                                                                          AND CATEGORIA.claID=ARTICULOS.CATEGORIA
                                                                                                          AND MODELO.mdID=ARTICULOS.MODELO
                                                                                                          AND CONDICION.cdID=CLIENTE.CONDICION
                                                                                                          AND CLIENTE.clID=OPERACIONES.INTERESADO
                                                                                                          AND ARTICULOS.artID=ARMADO.ID_ARTICULO_AR
                                                                                                          AND OPERACIONES.opID=ARMADO.OPERACION_REFERENCIA_AR
                                                                                                          AND PROOVEDOR.pooID=PRECIOS.PROOVEDOR
                                                                                                          AND opID=SOLICITUDES.REFERENCIA)
   JOIN PRHISTORICOS t1 ON(PRECIOS.RUBRO_pr=t1.RUBRO
                           AND PRECIOS.CATEGORIA_pr=t1.CATEGORIA
                           AND PRECIOS.MODELO_pr=t1.MODELO
                           AND t1.VIGENCIA<=SOLICITUDES.COMIENZO)
   LEFT JOIN PRHISTORICOS t2 ON(t1.RUBRO=t2.RUBRO
                                AND t1.CATEGORIA=t2.CATEGORIA
                                AND t1.MODELO=t2.MODELO
                                AND t2.VIGENCIA > t1.VIGENCIA
                                AND t2.VIGENCIA <=SOLICITUDES.COMIENZO)
   WHERE t2.VIGENCIA IS NULL
   	 AND CLASE=9
   GROUP BY DATE_FORMAT(SOLICITUDES.COMIENZO, '%Y-%m')
   ORDER BY YEAR(SOLICITUDES.COMIENZO),
            MONTH(SOLICITUDES.COMIENZO) ASC) t1
LEFT JOIN
  (SELECT DATE_FORMAT(OPERACIONES.FECHA, '%Y-%m') AS MES,
          ROUND(SUM(PERDIDAS), 2) AS PERDIDAS
   FROM CUENTA_CORRIENTE JOIN(OPERACIONES) ON(opID=OPERACION_REF_CC)
   GROUP BY DATE_FORMAT(OPERACIONES.FECHA, '%Y-%m')) t2 ON(t1.MES=t2.MES)
RIGHT JOIN
  (SELECT DATE_FORMAT(SOLICITUDES.COMIENZO, '%Y-%m') AS MES,
          SUM(MONTO) AS MONTO
   FROM COMISIONES JOIN(OPERACIONES,SOLICITUDES) ON(opID=OPERACION_REF_C
   	AND opID=SOLICITUDES.REFERENCIA)
   WHERE ((VIGENCIA IS NULL
          AND CANCELACION IS NULL)
     OR (VIGENCIA IS NULL
         AND CANCELACION IS NOT NULL))
	AND CLASE=9 
   GROUP BY DATE_FORMAT(SOLICITUDES.COMIENZO, '%Y-%m')) t3 ON(t1.MES=t3.MES)
LEFT JOIN
  (SELECT DATE_FORMAT(FECHA, '%Y-%m') AS MES,
          SUM(REGISTRO) AS REGISTRO
   FROM CONTABLES
   WHERE TIPO_REGISTRO=1
   GROUP BY DATE_FORMAT(FECHA, '%Y-%m')) t4 ON(t1.MES=t4.MES)
LEFT JOIN
  (SELECT DATE_FORMAT(FECHA, '%Y-%m') AS MES,
          SUM(REGISTRO) AS REGISTRO
   FROM CONTABLES
   WHERE TIPO_REGISTRO=2
   GROUP BY DATE_FORMAT(FECHA, '%Y-%m')) t5 ON(t1.MES=t5.MES)
LEFT JOIN
  (SELECT DATE_FORMAT(FECHA, '%Y-%m') AS MES,
          SUM(REGISTRO) AS REGISTRO
   FROM CONTABLES
   WHERE TIPO_REGISTRO=3
   GROUP BY DATE_FORMAT(FECHA, '%Y-%m')) t6 ON(t1.MES=t6.MES)
LEFT JOIN
  (SELECT DATE_FORMAT(FECHA, '%Y-%m') AS MES,
          SUM(REGISTRO) AS REGISTRO
   FROM CONTABLES
   WHERE TIPO_REGISTRO=6
   GROUP BY DATE_FORMAT(FECHA, '%Y-%m')) t9 ON(t1.MES=t9.MES)   
LEFT JOIN
  (SELECT DATE_FORMAT(OPERACIONES.FECHA, '%Y-%m') AS MES,
          SUM(DEBE-DEVOLUCION-PERDIDAS)*.04 AS INGRESO_PABLO
   FROM CUENTA_CORRIENTE JOIN(OPERACIONES) ON(opID=OPERACION_REF_CC)
   GROUP BY DATE_FORMAT(OPERACIONES.FECHA, '%Y-%m')) t7 ON(t1.MES=t7.MES)
LEFT JOIN
  (SELECT DATE_FORMAT(SOLICITUDES.COMIENZO, '%Y-%m') AS MES,
          ROUND(SUM(DEBE-IFNULL(DEVOLUCION, 0)), 2) AS NETO
   FROM CUENTA_CORRIENTE JOIN(OPERACIONES,SOLICITUDES) ON(opID=OPERACION_REF_CC AND REFERENCIA=opID)
   WHERE CLASE=9
   GROUP BY DATE_FORMAT(SOLICITUDES.COMIENZO, '%Y-%m')
   ORDER BY DATE_FORMAT(SOLICITUDES.COMIENZO, '%Y-%m') ASC) t8 ON(t1.MES=t8.MES);

