USE MIDOKA_PGC_B;
SELECT OPERACIONES.FECHA AS OPFECHA,REFERENCIA, SALDO_PROOVEDOR.FECHA AS SPFECHA, DEBE, HABER FROM SALDO_PROOVEDOR JOIN(OPERACIONES) ON(opID=OPERACION_ASOCIADA) ORDER BY OPERACIONES.FECHA DESC LIMIT 400;
