USE MIDOKA_PGC_B;
SELECT OPERACIONES.FECHA AS opFECHA,DENOMINACION,DEBE,opID
   FROM CUENTA_CORRIENTE
   JOIN(OPERACIONES,CLIENTE) ON(clID=INTERESADO AND opID=OPERACION_REF_CC)
   WHERE OPERACIONES.FECHA<='2019-12-31' AND DEBE>0 ORDER BY opID DESC;

SELECT OPERACIONES.FECHA AS opFECHA,SOLICITUDES.REALIZACION AS solFECHA,DENOMINACION,DEBE,opID
   FROM CUENTA_CORRIENTE
   JOIN(OPERACIONES,SOLICITUDES,CLIENTE) ON(clID=INTERESADO AND opID=OPERACION_REF_CC AND REFERENCIA=opID)
   WHERE SOLICITUDES.REALIZACION<='2019-12-31' AND CLASE=9 AND DEBE>0 ORDER BY opID DESC;

