USE MIDOKA_PGC_B;
USE MIDOKA_PGC_B
DROP PROCEDURE IF EXISTS TRANSACCION;
DELIMITER $$
CREATE PROCEDURE TRANSACCION()
BEGIN
DECLARE _rollback BOOL DEFAULT 0;
DECLARE A INT;
DECLARE B INT;
DECLARE C INT;
DECLARE D INT;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET _rollback = 1;
START TRANSACTION;
UPDATE MIDOKA_PGC_B.SOLICITUDES SET COMIENZO='2020-03-26',ASIGNADA=4 WHERE scID=41776;
UPDATE MIDOKA_PGC_B.SOLICITUDES SET REALIZACION='2020-03-26' WHERE scID=41775;
DELETE FROM MIDOKA_PGC_B.PEDIDO WHERE CANTIDAD=0;
INSERT INTO ARMADO (OPERACION_REFERENCIA_AR,ID_ARTICULO_AR,CANTIDAD_AR) VALUES ('10853','122','2');
INSERT INTO ARMADO (OPERACION_REFERENCIA_AR,ID_ARTICULO_AR,CANTIDAD_AR) VALUES ('10853','179','1');
INSERT INTO ARMADO (OPERACION_REFERENCIA_AR,ID_ARTICULO_AR,CANTIDAD_AR) VALUES ('10853','247','6');
INSERT INTO MIDOKA_PGC_B.BULTOS (OPERACION_REF,BULTOS) VALUES ('10853','2');
INSERT INTO LOCALIZACION_PEDIDO (OPERACION_REF,LOCALIZACION) VALUES ('10853','1');
DELETE FROM MIDOKA_PGC_B.ARMADO WHERE CANTIDAD_AR=0 AND CANTIDAD_EGR IS NULL AND CANTIDAD_ING IS NULL AND CANTIDAD_DEVOL IS NULL AND CANTIDAD_CST IS NULL;
UPDATE SOLICITUDES SET REALIZACION='2020-03-26' WHERE ASIGNADA=4 AND REFERENCIA=10853;
UPDATE SOLICITUDES SET COMIENZO='2020-03-26' WHERE scID=41778 AND REFERENCIA=10853;
SELECT 'ERROR' FROM BULTOS WHERE NOT EXISTS (SELECT * FROM BULTOS WHERE OPERACION_REF=10853) LIMIT 1;
SELECT 'ERROR' FROM LOCALIZACION_PEDIDO WHERE NOT EXISTS (SELECT * FROM LOCALIZACION_PEDIDO WHERE OPERACION_REF=10853) LIMIT 1;
SELECT 'ERROR' FROM ARMADO WHERE NOT EXISTS (SELECT * FROM ARMADO WHERE OPERACION_REFERENCIA_AR=10853) LIMIT 1;
SELECT COUNT(CANTIDAD_AR) FROM ARMADO WHERE OPERACION_REFERENCIA_AR=10853 INTO A;
SELECT COUNT(BULTOS) FROM BULTOS WHERE OPERACION_REF=10853 INTO B;
SELECT COUNT(LOCALIZACION) FROM LOCALIZACION_PEDIDO WHERE OPERACION_REF=10853 INTO C;
SELECT A + B + C INTO D;
IF(D < 3) THEN
SIGNAL SQLSTATE '45000';
END IF;
IF _rollback THEN
ROLLBACK;
SELECT 'ERROR';
ELSE
COMMIT;
END IF;
END$$
DELIMITER ;
CALL TRANSACCION;
