USE MIDOKA_PGC_B;
USE MIDOKA_PGC_B
DROP PROCEDURE IF EXISTS TRANSACCION;
DELIMITER $$
CREATE PROCEDURE TRANSACCION()
BEGIN
DECLARE _rollback BOOL DEFAULT 0;
DECLARE A INT;
DECLARE B INT;
DECLARE C INT;
DECLARE D INT;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET _rollback = 1;
START TRANSACTION;
INSERT INTO MIDOKA_PGC_B.COMISIONES (OPERACION_REF_C,TRABAJADOR,MONTO) VALUES (10853,4,0.0);
INSERT INTO MIDOKA_PGC_B.COMISIONES (OPERACION_REF_C,TRABAJADOR,MONTO) VALUES (10853,5,4.07);
INSERT INTO MIDOKA_PGC_B.CUENTA_CORRIENTE (OPERACION_REF_CC,DEBE,HABER,DEVOLUCION,PERDIDAS) VALUES(10853,813.56,0,0,0);
IF _rollback THEN
ROLLBACK;
SELECT 'ERROR';
ELSE
COMMIT;
END IF;
END$$
DELIMITER ;
CALL TRANSACCION;
