USE MIDOKA_PGC_B;
USE MIDOKA_PGC_B
DROP PROCEDURE IF EXISTS TRANSACCION;
DELIMITER $$
CREATE PROCEDURE TRANSACCION()
BEGIN
DECLARE _rollback BOOL DEFAULT 0;
DECLARE A INT;
DECLARE B INT;
DECLARE C INT;
DECLARE D INT;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET _rollback = 1;
START TRANSACTION;
INSERT INTO MIDOKA_PGC_B.SOLICITUDES (REFERENCIA,CLASE,ASIGNADA,COMIENZO) VALUES (10853,4,5,'2020-03-26');
INSERT INTO MIDOKA_PGC_B.SOLICITUDES (REFERENCIA,CLASE,ASIGNADA) VALUES (10853,5,5);
INSERT INTO MIDOKA_PGC_B.SOLICITUDES (REFERENCIA,CLASE,ASIGNADA) VALUES (10853,6,4);
INSERT INTO MIDOKA_PGC_B.SOLICITUDES (REFERENCIA,CLASE,ASIGNADA) VALUES (10853,7,9);
INSERT INTO MIDOKA_PGC_B.SOLICITUDES (REFERENCIA,CLASE,ASIGNADA) VALUES (10853,8,5);
INSERT INTO MIDOKA_PGC_B.SOLICITUDES (REFERENCIA,CLASE,ASIGNADA) VALUES (10853,9,0);
INSERT INTO MIDOKA_PGC_B.SOLICITUDES (REFERENCIA,CLASE,ASIGNADA) VALUES (10853,10,5);
IF _rollback THEN
ROLLBACK;
SELECT 'ERROR';
ELSE
COMMIT;
END IF;
END$$
DELIMITER ;
CALL TRANSACCION;
