USE MIDOKA_PGC_B;
USE MIDOKA_PGC_B
DROP PROCEDURE IF EXISTS TRANSACCION;
DELIMITER $$
CREATE PROCEDURE TRANSACCION()
BEGIN
DECLARE _rollback BOOL DEFAULT 0;
DECLARE A INT;
DECLARE B INT;
DECLARE C INT;
DECLARE D INT;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET _rollback = 1;
START TRANSACTION;
INSERT INTO MIDOKA_PGC_B.SALDO_PROOVEDOR (FECHA,REFERENCIA,PROOVEDOR,DEBE,HABER,OPERACION_ASOCIADA) VALUES ('	2019-12-18','1812 ULTIMA',2,42761.4,'0',10139);
INSERT INTO MIDOKA_PGC_B.ARMADO (ID_ARTICULO_AR,CANTIDAD_ING,OPERACION_REFERENCIA_AR) VALUES(286,5,10139);
INSERT INTO MIDOKA_PGC_B.ARMADO (ID_ARTICULO_AR,CANTIDAD_ING,OPERACION_REFERENCIA_AR) VALUES(287,15,10139);
INSERT INTO MIDOKA_PGC_B.ARMADO (ID_ARTICULO_AR,CANTIDAD_ING,OPERACION_REFERENCIA_AR) VALUES(289,20,10139);
INSERT INTO MIDOKA_PGC_B.ARMADO (ID_ARTICULO_AR,CANTIDAD_ING,OPERACION_REFERENCIA_AR) VALUES(290,40,10139);
INSERT INTO MIDOKA_PGC_B.ARMADO (ID_ARTICULO_AR,CANTIDAD_ING,OPERACION_REFERENCIA_AR) VALUES(291,25,10139);
INSERT INTO MIDOKA_PGC_B.ARMADO (ID_ARTICULO_AR,CANTIDAD_ING,OPERACION_REFERENCIA_AR) VALUES(292,20,10139);
INSERT INTO MIDOKA_PGC_B.ARMADO (ID_ARTICULO_AR,CANTIDAD_ING,OPERACION_REFERENCIA_AR) VALUES(294,15,10139);
INSERT INTO MIDOKA_PGC_B.ARMADO (ID_ARTICULO_AR,CANTIDAD_ING,OPERACION_REFERENCIA_AR) VALUES(295,5,10139);
INSERT INTO MIDOKA_PGC_B.ARMADO (ID_ARTICULO_AR,CANTIDAD_ING,OPERACION_REFERENCIA_AR) VALUES(296,5,10139);
INSERT INTO MIDOKA_PGC_B.ARMADO (ID_ARTICULO_AR,CANTIDAD_ING,OPERACION_REFERENCIA_AR) VALUES(297,5,10139);
IF _rollback THEN
ROLLBACK;
SELECT 'ERROR';
ELSE
COMMIT;
END IF;
END$$
DELIMITER ;
CALL TRANSACCION;
