USE MIDOKA_PGC_B;
USE MIDOKA_PGC_B
DROP PROCEDURE IF EXISTS TRANSACCION;
DELIMITER $$
CREATE PROCEDURE TRANSACCION()
BEGIN
DECLARE _rollback BOOL DEFAULT 0;
DECLARE A INT;
DECLARE B INT;
DECLARE C INT;
DECLARE D INT;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET _rollback = 1;
START TRANSACTION;
UPDATE MIDOKA_PGC_B.SOLICITUDES SET COMIENZO='2020-03-18',ASIGNADA=4 WHERE scID=36718;
UPDATE MIDOKA_PGC_B.SOLICITUDES SET REALIZACION='2020-03-18' WHERE scID=36717;
IF _rollback THEN
ROLLBACK;
SELECT 'ERROR';
ELSE
COMMIT;
END IF;
END$$
DELIMITER ;
CALL TRANSACCION;
