### GENERAL ########
SELECT mod_md,CONCAT(ROUND((t2.PRECIO / t1.PRECIO - 1) *100,2),' %') FROM PRHISTORICOS t1 LEFT JOIN PRHISTORICOS t2 ON(t1.RUBRO=t2.RUBRO AND t1.CATEGORIA=t2.CATEGORIA AND t1.MODELO=t2.MODELO AND t2.VIGENCIA>t1.VIGENCIA) JOIN(MODELO) ON(MODELO.mdID=t1.MODELO) WHERE t2.PRECIO IS NOT NULL AND t1.VIGENCIA='2018-05-17' AND ROUND((t2.PRECIO / t1.PRECIO - 1) *100,2)>0;

