
mysql -u root --execute="USE MIDOKA_PGC_B;SELECT FECHA,DENOMINACION,opID FROM COMISIONES JOIN(CLIENTE,OPERACIONES) ON(OPERACIONES.opID=COMISIONES.OPERACION_REF_C AND OPERACIONES.INTERESADO=CLIENTE.clID) GROUP BY OPERACION_REF_C;">comisiones_efectivas
mysql -u root --execute="USE MIDOKA_PGC_B;SELECT FECHA,DENOMINACION,opID FROM SOLICITUDES JOIN(CLIENTE,OPERACIONES) ON(OPERACIONES.opID=SOLICITUDES.REFERENCIA AND OPERACIONES.INTERESADO=CLIENTE.clID) WHERE REALIZACION IS NOT NULL AND CLASE='9' GROUP BY REFERENCIA;" >cargas_efectivas
diff comisiones_efectivas cargas_efectivas 
