#!/bin/bash
#
#
#
# 
# 
#
# 
#
# 
# # SCRIPT para el seleccionado de la orden de carga a realizar

################### MANTENIMIENTO INICIAL #####################


#shopt -s -o unset

################### DECLARACIONES ########################

declare -r ARCHIVO="$1"

declare TOTAL

declare CONTADOR

declare ENTRADA="9"

declare MONTO

declare -a COMISIONES=("VENTA.fact" "DEPOSITO.fact" "ADMINISTRACION.fact")

declare RECURSO_HUMANO

declare COMISIONA_MARCE=""

declare CARPETA_TRABAJO="${DIA}-${SESION_ID}"


#@@@@@@@@@@@@@@@@@ FUNCIONES @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

function facturar_render {

    #enscript -B ""${temp}"tmp3.fact" -p ""${temp}"/"${line}".eps"

    paps --font=Monospace\ 8 ""${temp}"tmp3.fact" >""${temp}"/"${line}".eps"
    
    cp ""${temp}"/"${line}".eps" ""${HOME}"/Dropbox/RODRIGO/ULTIMAS_ENTREGAS/"${CARPETA_TRABAJO}"/"

    cp ""${temp}"/"${line}".eps" ${fact}
    

}


function escritura_faltante {

    echo -e "${AVISO_FALTANTE}\n" >> ${temp}"tmp3.fact"
    
    mysql -u "${user}" --password="${pass}" --execute="USE "${DB}";SELECT TRES,CONCAT(' ',CUATRO) FROM CHINO WHERE chinoID=3;" | tail -n +2 >${temp}"tmp31.fact"

    mysql -u "${user}" --password="${pass}" --execute="USE "${DB}";SELECT CONCAT(clasificacion_cla,' ',mod_md,' ',motivo_mt) AS 'ARTICULO',CANTIDAD_FL AS 'FALTANTE#' FROM FALTANTE JOIN (OPERACIONES,ARTICULOS,CATEGORIA,MODELO,MOTIVO) ON (FALTANTE.OPERACION_REFERENCIA_FL=OPERACIONES.opID AND FALTANTE.ID_ARTICULO_FL=ARTICULOS.artID AND FALTANTE.OPERACION_REFERENCIA_FL=OPERACIONES.opID AND ARTICULOS.CATEGORIA=CATEGORIA.claID AND ARTICULOS.MODELO=MODELO.mdID AND ARTICULOS.MOTIVO=MOTIVO.mtID) WHERE OPERACIONES.opID="${line}" ORDER BY CATEGORIA,MODELO,MOTIVO;" >>${temp}"tmp31.fact" 
    
    cat ${temp}"tmp31.fact" | column -t -s $'\t' | sed 's/#$/\n/g' >>${temp}"tmp3.fact"
  
    
}

   
#@@@@@@@@@@@@@@@@@@ SCRIPT ##################################	


mkdir ""${HOME}"/Dropbox/RODRIGO/ULTIMAS_ENTREGAS/"${CARPETA_TRABAJO}"" && mkdir ""${HOME}"/Dropbox/RODRIGO/ULTIMAS_ENTREGAS/"${CARPETA_TRABAJO}"/VISTA_MARCE_PDF" 

AGMYSQL=""${temp}"/"${RANDOM}".grabado"

rm ${AGMYSQL}

test -f "${AGMYSQL}" || touch "${AGMYSQL}"


while read line; do

    echo -e "__________________________________________________________________________________________\n" >${temp}"tmp3.fact"

    mysql -u "${user}" --password="${pass}" --execute="SELECT UNO,CONCAT(' ',DOS),CONCAT('  ',TRES),CONCAT('  ',CUATRO),CONCAT('   ',CINCO),CONCAT('    ',SEIS),CONCAT('    ',SIETE) FROM "${DB}".CHINO WHERE chinoID=1;" | tail -n +2 | tr '\t' ',' >${temp}"tmp31.fact"
    
    mysql -u "${user}" --password="${pass}" --execute="SELECT opID AS REMITO,CURRENT_DATE() AS FECHA,DENOMINACION AS NOMBRE,BULTOS,DIRECCION,SUBSTRING(estaf_lc,1,12) AS LOCALIDAD,HORARIO AS 'HORARIO#' FROM "${DB}".SOLICITUDES JOIN("${DB}".CLIENTE,"${DB}".OPERACIONES,"${DB}".BULTOS,"${DB}".LOCALIZACION_PEDIDO,"${DB}".LOCALIDAD,"${DB}".LOCACIONES_DEPOSITO) ON("${DB}".SOLICITUDES.REFERENCIA="${DB}".OPERACIONES.opID AND "${DB}".OPERACIONES.INTERESADO="${DB}".CLIENTE.clID AND "${DB}".SOLICITUDES.REFERENCIA="${DB}".BULTOS.OPERACION_REF AND "${DB}".SOLICITUDES.REFERENCIA="${DB}".LOCALIZACION_PEDIDO.OPERACION_REF AND "${DB}".LOCALIDAD.lcID="${DB}".CLIENTE.LOCALIDAD AND "${DB}".LOCACIONES_DEPOSITO.locdepID="${DB}".LOCALIZACION_PEDIDO.LOCALIZACION) WHERE REFERENCIA="${line}" GROUP BY REFERENCIA;" | tr '\t' ',' >>${temp}"tmp31.fact"

    

    # SACO EL TITULO , LO ALINEO CON LO CHINO , LE PEGO LOS DATOS
    

    
    cat ${temp}"tmp31.fact" | column -t -s $',' >>${temp}"tmp3.fact"

    
    
    echo -e "__________________________________________________________________________________________\n" >>${temp}"tmp3.fact"

    
    
    mysql -u "${user}" --password="${pass}" --execute="SELECT UNO,DOS,CONCAT('  ',TRES),CONCAT('   ',CUATRO),CONCAT('   ',CINCO),CONCAT('    ',SEIS),CONCAT('     ',SIETE) FROM "${DB}".CHINO WHERE chinoID=2;" | tail -n +2 | tr '\t' ',' >${temp}"tmp31.fact"

    mysql -u "${user}" --password="${pass}" --execute="SELECT CODIGO_BARRAS AS CODIGO,CONCAT(clasificacion_cla,' ',mod_md,'  ',DESCRIPCION_CHINO) AS DESCRIPCION,IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) AS CANTIDAD,ROUND(IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2) AS PRECIO,ROUND(IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2) AS MONTO,IF(CONDICION = CONDICION_REFERENCIA AND DESCUENTO_ESPECIAL <> '-',CONCAT(DESCUENTO_ESPECIAL,'%'),IF(DESCUENTO_ESPECIFICO > '0',CONCAT(DESCUENTO_ESPECIFICO,'%'),CONCAT(cond_num_fact,'%'))) AS 'DESC',IF(CONDICION = CONDICION_REFERENCIA AND DESCUENTO_ESPECIAL <> '-',ROUND(ROUND(1 - DESCUENTO_ESPECIAL/100,2) * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),IF(DESCUENTO_ESPECIFICO > '0',ROUND(ROUND(1 - DESCUENTO_ESPECIFICO/100,2) * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),ROUND(cond_num_cd * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2))) AS 'SUB-TOTAL#' FROM "${DB}".ARMADO JOIN("${DB}".PRECIOS,"${DB}".CATEGORIA,"${DB}".MODELO,"${DB}".CONDICION,"${DB}".ARTICULOS,"${DB}".CLIENTE,"${DB}".OPERACIONES,"${DB}".PROOVEDOR) ON("${DB}".PRECIOS.RUBRO_pr="${DB}".ARTICULOS.RUBRO AND "${DB}".PRECIOS.CATEGORIA_pr="${DB}".ARTICULOS.CATEGORIA AND "${DB}".PRECIOS.MODELO_pr="${DB}".ARTICULOS.MODELO AND "${DB}".CATEGORIA.claID="${DB}".ARTICULOS.CATEGORIA AND "${DB}".MODELO.mdID="${DB}".ARTICULOS.MODELO AND "${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".CLIENTE.clID="${DB}".OPERACIONES.INTERESADO AND "${DB}".ARTICULOS.artID="${DB}".ARMADO.ID_ARTICULO_AR AND "${DB}".OPERACIONES.opID="${DB}".ARMADO.OPERACION_REFERENCIA_AR AND "${DB}".PROOVEDOR.pooID="${DB}".PRECIOS.PROOVEDOR) WHERE opID="${line}" GROUP BY CATEGORIA, MODELO ;" | tr '\t' ',' >>${temp}"tmp31.fact"

    # SACO EL TITULO , LO ALINEO CON LO CHINO , LE PEGO LOS DATOS

    
        
    mysql -u "${user}" --password="${pass}" --execute="SELECT IF(CONDICION = CONDICION_REFERENCIA AND DESCUENTO_ESPECIAL <> '-',ROUND(ROUND(1 - DESCUENTO_ESPECIAL/100,2) * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),IF(DESCUENTO_ESPECIFICO > '0',ROUND(ROUND(1 - DESCUENTO_ESPECIFICO/100,2) * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),ROUND(cond_num_cd * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2))) AS 'SUB-TOTAL#' FROM "${DB}".ARMADO JOIN("${DB}".PRECIOS,"${DB}".CATEGORIA,"${DB}".MODELO,"${DB}".CONDICION,"${DB}".ARTICULOS,"${DB}".CLIENTE,"${DB}".OPERACIONES,"${DB}".PROOVEDOR) ON("${DB}".PRECIOS.RUBRO_pr="${DB}".ARTICULOS.RUBRO AND "${DB}".PRECIOS.CATEGORIA_pr="${DB}".ARTICULOS.CATEGORIA AND "${DB}".PRECIOS.MODELO_pr="${DB}".ARTICULOS.MODELO AND "${DB}".CATEGORIA.claID="${DB}".ARTICULOS.CATEGORIA AND "${DB}".MODELO.mdID="${DB}".ARTICULOS.MODELO AND "${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".CLIENTE.clID="${DB}".OPERACIONES.INTERESADO AND "${DB}".ARTICULOS.artID="${DB}".ARMADO.ID_ARTICULO_AR AND "${DB}".OPERACIONES.opID="${DB}".ARMADO.OPERACION_REFERENCIA_AR AND "${DB}".PROOVEDOR.pooID="${DB}".PRECIOS.PROOVEDOR) WHERE opID="${line}" GROUP BY CATEGORIA, MODELO ;" | tail -n +2 >${temp}"tmp6.fact"


    mysql -u "${user}" --password="${pass}" --execute="SELECT ASIGNADA,ROUND(VENTA * IF(CONDICION = CONDICION_REFERENCIA AND DESCUENTO_ESPECIAL <> '-',ROUND(ROUND(1 - DESCUENTO_ESPECIAL/100,2) * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),IF(DESCUENTO_ESPECIFICO > '0',ROUND(ROUND(1 - DESCUENTO_ESPECIFICO/100,2) * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),ROUND(cond_num_cd * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2))),2) AS 'SUB-TOTAL#' FROM "${DB}".ARMADO JOIN("${DB}".PRECIOS,"${DB}".CATEGORIA,"${DB}".MODELO,"${DB}".CONDICION,"${DB}".ARTICULOS,"${DB}".CLIENTE,"${DB}".OPERACIONES,"${DB}".PROOVEDOR,"${DB}".SOLICITUDES,"${DB}".TIPO_COMISION) ON("${DB}".PRECIOS.RUBRO_pr="${DB}".ARTICULOS.RUBRO AND "${DB}".PRECIOS.CATEGORIA_pr="${DB}".ARTICULOS.CATEGORIA AND "${DB}".PRECIOS.MODELO_pr="${DB}".ARTICULOS.MODELO AND "${DB}".CATEGORIA.claID="${DB}".ARTICULOS.CATEGORIA AND "${DB}".MODELO.mdID="${DB}".ARTICULOS.MODELO AND "${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".CLIENTE.clID="${DB}".OPERACIONES.INTERESADO AND "${DB}".ARTICULOS.artID="${DB}".ARMADO.ID_ARTICULO_AR AND "${DB}".OPERACIONES.opID="${DB}".ARMADO.OPERACION_REFERENCIA_AR AND "${DB}".PROOVEDOR.pooID="${DB}".PRECIOS.PROOVEDOR AND "${DB}".OPERACIONES.opID="${DB}".SOLICITUDES.REFERENCIA AND "${DB}".PRECIOS.TIPO_COMISION="${DB}".TIPO_COMISION.tcoID) WHERE opID="${line}" AND CLASE='2' GROUP BY CATEGORIA, MODELO ;" | tail -n +2 >${temp}"VENTA.fact"


    mysql -u "${user}" --password="${pass}" --execute="SELECT ASIGNADA,ROUND(DEPOSITO * IF(CONDICION = CONDICION_REFERENCIA AND DESCUENTO_ESPECIAL <> '-',ROUND(ROUND(1 - DESCUENTO_ESPECIAL/100,2) * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),IF(DESCUENTO_ESPECIFICO > '0',ROUND(ROUND(1 - DESCUENTO_ESPECIFICO/100,2) * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),ROUND(cond_num_cd * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2))),2) AS 'SUB-TOTAL#' FROM "${DB}".ARMADO JOIN("${DB}".PRECIOS,"${DB}".CATEGORIA,"${DB}".MODELO,"${DB}".CONDICION,"${DB}".ARTICULOS,"${DB}".CLIENTE,"${DB}".OPERACIONES,"${DB}".PROOVEDOR,"${DB}".SOLICITUDES,"${DB}".TIPO_COMISION) ON("${DB}".PRECIOS.RUBRO_pr="${DB}".ARTICULOS.RUBRO AND "${DB}".PRECIOS.CATEGORIA_pr="${DB}".ARTICULOS.CATEGORIA AND "${DB}".PRECIOS.MODELO_pr="${DB}".ARTICULOS.MODELO AND "${DB}".CATEGORIA.claID="${DB}".ARTICULOS.CATEGORIA AND "${DB}".MODELO.mdID="${DB}".ARTICULOS.MODELO AND "${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".CLIENTE.clID="${DB}".OPERACIONES.INTERESADO AND "${DB}".ARTICULOS.artID="${DB}".ARMADO.ID_ARTICULO_AR AND "${DB}".OPERACIONES.opID="${DB}".ARMADO.OPERACION_REFERENCIA_AR AND "${DB}".PROOVEDOR.pooID="${DB}".PRECIOS.PROOVEDOR AND "${DB}".OPERACIONES.opID="${DB}".SOLICITUDES.REFERENCIA AND "${DB}".PRECIOS.TIPO_COMISION="${DB}".TIPO_COMISION.tcoID) WHERE opID="${line}" AND CLASE='6' GROUP BY CATEGORIA, MODELO ;" | tail -n +2 >${temp}"DEPOSITO.fact"

    mysql -u "${user}" --password="${pass}" --execute="SELECT ASIGNADA,ROUND(ADMINISTRACION * IF(CONDICION = CONDICION_REFERENCIA AND DESCUENTO_ESPECIAL <> '-',ROUND(ROUND(1 - DESCUENTO_ESPECIAL/100,2) * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),IF(DESCUENTO_ESPECIFICO > '0',ROUND(ROUND(1 - DESCUENTO_ESPECIFICO/100,2) * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),ROUND(cond_num_cd * IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,SUM(CANTIDAD_AR) * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2))),2) AS 'SUB-TOTAL#' FROM "${DB}".ARMADO JOIN("${DB}".PRECIOS,"${DB}".CATEGORIA,"${DB}".MODELO,"${DB}".CONDICION,"${DB}".ARTICULOS,"${DB}".CLIENTE,"${DB}".OPERACIONES,"${DB}".PROOVEDOR,"${DB}".SOLICITUDES,"${DB}".TIPO_COMISION) ON("${DB}".PRECIOS.RUBRO_pr="${DB}".ARTICULOS.RUBRO AND "${DB}".PRECIOS.CATEGORIA_pr="${DB}".ARTICULOS.CATEGORIA AND "${DB}".PRECIOS.MODELO_pr="${DB}".ARTICULOS.MODELO AND "${DB}".CATEGORIA.claID="${DB}".ARTICULOS.CATEGORIA AND "${DB}".MODELO.mdID="${DB}".ARTICULOS.MODELO AND "${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".CLIENTE.clID="${DB}".OPERACIONES.INTERESADO AND "${DB}".ARTICULOS.artID="${DB}".ARMADO.ID_ARTICULO_AR AND "${DB}".OPERACIONES.opID="${DB}".ARMADO.OPERACION_REFERENCIA_AR AND "${DB}".PROOVEDOR.pooID="${DB}".PRECIOS.PROOVEDOR AND "${DB}".OPERACIONES.opID="${DB}".SOLICITUDES.REFERENCIA AND "${DB}".PRECIOS.TIPO_COMISION="${DB}".TIPO_COMISION.tcoID) WHERE opID="${line}" AND CLASE='4' GROUP BY CATEGORIA, MODELO ;" | tail -n +2 >${temp}"ADMINISTRACION.fact"

   # GRABADO DE LAS COMISIONES EN CASO DE QUE EXISTAN


   #mysql -u "${user}" --password="${pass}" --execute="SELECT DATE_ADD(CURDATE(),INTERVAL 15 DAY);" >${temp}"vigencia.fact"
    
   #VIGENCIA="$(cat ${temp}"vigencia.fact" | tail -n +2)"

     
   for i in ${COMISIONES[@]};do

       declare SUMA=0    
       
       TOTAL=0

       RECURSO_HUMANO="$(cat ${temp}"${i}" | head -1 | awk '{print $1}')"
       
       while read line_c;do

	   SUMA="$(echo "${line_c}" | awk '{print $NF}')"
	   
	   TOTAL="$(maxima --very-quiet --batch-string "fpprintprec:7$"${TOTAL}"+"${SUMA}";" | tail -n +3 | sed /^[0-9]/d | sed s/[[:blank:]]//g)"
	   
       done<${temp}"${i}"

       
       
       test -z "${RECURSO_HUMANO}" || echo "INSERT INTO "${DB}".COMISIONES (OPERACION_REF_C,TRABAJADOR,MONTO) VALUES ("${line}","${RECURSO_HUMANO}","${TOTAL}");" >>${AGMYSQL}

       
       
       case $i in
	   "VENTA.fact") rm ""${temp}"tmp_data_cont.fact"
	                 test -z "${RECURSO_HUMANO}" || mysql -u "${user}" --password="${pass}" --execute="SELECT nombre_rhd FROM "${DB}".RECURSOS_HUMANOS_DISPONIBLES WHERE rhdID="${RECURSO_HUMANO}";" | tail -n +2 >""${temp}"tmp_data_cont.fact" 
			 COMISIONA_MARCE="$(cat ""${temp}"tmp_data_cont.fact" | egrep -o '\b\w' | tr '\n' ' ')" || COMISIONA_MARCE="" 
			 ;;
       esac

   done
   
       
   # CALUCLO DEL MONTO TOTAL DEL REMITO

   TOTAL=0
   
   while read line_b; do
       TOTAL="$(maxima --very-quiet --batch-string "fpprintprec:7$"${TOTAL}"+"${line_b}";" | tail -n +3 | sed /^[0-9]/d | sed s/[[:blank:]]//g)"
       
   done<${temp}"tmp6.fact"

   
   echo -e " , , , , , ,_________\n" >>${temp}"tmp31.fact"

   echo -e " , , ,总计,TOTAL,-->,"${TOTAL}"\n">>${temp}"tmp31.fact"
    
   
   cat ${temp}"tmp31.fact" | column -t -s $',' >${temp}"tmp5.fact"

      
   echo "$(cat ${temp}"tmp5.fact")">>${temp}"tmp3.fact"

   MONTO="${TOTAL}"

   echo -e "\n CAT.: "${COMISIONA_MARCE}"\n\n">>${temp}"tmp3.fact"

   # DATOS DE CONTACTO

   echo -e "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - " >>${temp}"tmp3.fact"
   
   mysql -u "${user}" --password="${pass}" --execute="USE "${DB}";SELECT CONCAT(UNO,'--> ',DOS,' | ',TRES,' | ',CUATRO,'      | ',CINCO,' | ',SEIS) FROM CHINO WHERE chinoID=4;" | tail -n +2 >>${temp}"tmp3.fact"

   echo -e "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n" >>${temp}"tmp3.fact"

   # REVISO SI ENTRA EN ALGUNA PROMOCION Y LA ASGINO

   
   TOTAL="$(mysql -u "${user}" --password="${pass}" --execute="SELECT IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,REGALO * CANTIDAD_MINIMA,'NULL') AS CANTIDAD FROM "${DB}".ARMADO JOIN("${DB}".PRECIOS,"${DB}".CATEGORIA,"${DB}".MODELO,"${DB}".CONDICION,"${DB}".ARTICULOS,"${DB}".CLIENTE,"${DB}".OPERACIONES) ON("${DB}".PRECIOS.RUBRO_pr="${DB}".ARTICULOS.RUBRO AND "${DB}".PRECIOS.CATEGORIA_pr="${DB}".ARTICULOS.CATEGORIA AND "${DB}".PRECIOS.MODELO_pr="${DB}".ARTICULOS.MODELO AND "${DB}".CATEGORIA.claID="${DB}".ARTICULOS.CATEGORIA AND "${DB}".MODELO.mdID="${DB}".ARTICULOS.MODELO AND "${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".CLIENTE.clID="${DB}".OPERACIONES.INTERESADO AND "${DB}".ARTICULOS.artID="${DB}".ARMADO.ID_ARTICULO_AR AND "${DB}".OPERACIONES.opID="${DB}".ARMADO.OPERACION_REFERENCIA_AR) WHERE opID="${line}" GROUP BY CATEGORIA, MODELO ;" | tail -n +2 |grep -v 'NULL')"




   if test ! -z """${TOTAL}"""; then

       echo -e "__________________________________________________________________________________________\n" >>${temp}"tmp3.fact"

       echo -e "EN OBSEQUIO POR PROMOCION                                                                 \n" >>${temp}"tmp3.fact"

       mysql -u "${user}" --password="${pass}" --execute="SELECT IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,CODIGO_BARRAS,'') AS CODIGO,IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,CONCAT(clasificacion_cla,' ',mod_md),'') AS DESCRIPCION,IF(UMBRAL>0 AND SUM(CANTIDAD_AR)>=UMBRAL,REGALO * CANTIDAD_MINIMA,'') AS 'CANTIDAD#' FROM "${DB}".ARMADO JOIN("${DB}".PRECIOS,"${DB}".CATEGORIA,"${DB}".MODELO,"${DB}".CONDICION,"${DB}".ARTICULOS,"${DB}".CLIENTE,"${DB}".OPERACIONES) ON("${DB}".PRECIOS.RUBRO_pr="${DB}".ARTICULOS.RUBRO AND "${DB}".PRECIOS.CATEGORIA_pr="${DB}".ARTICULOS.CATEGORIA AND "${DB}".PRECIOS.MODELO_pr="${DB}".ARTICULOS.MODELO AND "${DB}".CATEGORIA.claID="${DB}".ARTICULOS.CATEGORIA AND "${DB}".MODELO.mdID="${DB}".ARTICULOS.MODELO AND "${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".CLIENTE.clID="${DB}".OPERACIONES.INTERESADO AND "${DB}".ARTICULOS.artID="${DB}".ARMADO.ID_ARTICULO_AR AND "${DB}".OPERACIONES.opID="${DB}".ARMADO.OPERACION_REFERENCIA_AR) WHERE opID="${line}" GROUP BY CATEGORIA, MODELO ;" | column -t -s $'\t'>>${temp}"tmp3.fact"

       #cat ${temp}"tmp3.fact" | column -t -s $'\t' >${temp}"tmp3.fact"
       
       
       echo -e "__________________________________________________________________________________________\n" >>${temp}"tmp3.fact"
       

     
       
   
       
   fi

   # TESTEO SI HAY FALTANTES

   echo " " >${temp}"tmp32.fact" && echo " " >${temp}"tmp31.fact"
   
   AVISO_FALTANTE="$(mysql -u "${user}" --password="${pass}" --execute="USE "${DB}";SELECT CONCAT(DOS,';',UNO) FROM CHINO WHERE chinoID=3;" | tail -n +2 | tr ';' '\n')"

     
   test ! -z "$(mysql -u "${user}" --password="${pass}" --execute="USE "${DB}";SELECT CONCAT(clasificacion_cla,' ',mod_md,' ',motivo_mt) AS 'ARTICULO',CANTIDAD_FL AS 'FALTANTE#' FROM FALTANTE JOIN (OPERACIONES,ARTICULOS,CATEGORIA,MODELO,MOTIVO) ON (FALTANTE.OPERACION_REFERENCIA_FL=OPERACIONES.opID AND FALTANTE.ID_ARTICULO_FL=ARTICULOS.artID AND FALTANTE.OPERACION_REFERENCIA_FL=OPERACIONES.opID AND ARTICULOS.CATEGORIA=CATEGORIA.claID AND ARTICULOS.MODELO=MODELO.mdID AND ARTICULOS.MOTIVO=MOTIVO.mtID) WHERE OPERACIONES.opID="${line}" ORDER BY CATEGORIA,MODELO,MOTIVO;" | head -1)" && escritura_faltante
   
   # RENDERIZADO DE LA FACTURA
   
   sed -i 's/#$/\n/g' ${temp}"tmp3.fact"

   #cat ${temp}"tmp3.fact" | column -t -s $'\t' >${temp}"tmp3.fact"
   
   # ASIGNO EL MONTO A LA CUENTA CORRIENTE DEL CLIENTE

   echo "INSERT INTO "${DB}".CUENTA_CORRIENTE (OPERACION_REF_CC,DEBE,HABER,DEVOLUCION,PERDIDAS) VALUES("${line}","${MONTO}",0,0,0);" >>${AGMYSQL}

   facturar_render ; #enscript -B ${temp}"tmp3.fact" ${temp}"tmp3.fact" -p ${imp}"/"${user}"/"${line}".eps"
   
   paps --font=Monospace\ 8 ""${temp}"tmp3.fact" >${REPARTO}"/"${line}".eps"

   paps --font=Monospace\ 8 ""${temp}"tmp3.fact" >${REPARTO}"/"${line}"-2.eps"
   
done<${ARCHIVO}

dataFecha="${DIA}-${RANDOM}"

gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER -sOutputFile=${imp}/repartos/trabajosHistoricos/"${dataFecha}".pdf ${REPARTO}/*.eps

gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER -sOutputFile=${HOME}/Dropbox/RODRIGO/ULTIMAS_ENTREGAS/"${CARPETA_TRABAJO}"/"${dataFecha}"-IMPRESION-RODRIGO.pdf ${REPARTO}/*.eps

cp ${REPARTO}/*.eps ${imp}/repartos/colaImpresion/

## Grabacion de saldos

bash ${scr}"transaccion.sh" "${AGMYSQL}" || dialog --msgbox "OCURRIO UN ERROR EN EL PROCESO LLAMAR A NICO URGENTE POR FAVOR" 0 0


## PARTE PARA MARCE

cd ""${HOME}"/Dropbox/RODRIGO/ULTIMAS_ENTREGAS/"${CARPETA_TRABAJO}"/"

gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER -sOutputFile=""${HOME}"/Dropbox/RODRIGO/ULTIMAS_ENTREGAS/"${CARPETA_TRABAJO}"/VISTA_MARCE_PDF/"${DIA}".pdf" *.eps


# ## Envio por correo

# python ${scr}envia_mail.py ${imp}repartos/trabajosHistoricos/"${dataFecha}".pdf &

################## MANTENIMIENTO FINAL ###################


VAR_s=${temp}"*.fact" 

rm $VAR_s

exit 192
