#!/bin/bash
#
#
#
# 
# 
#
# 
#
# 
# # SCRIPT para el seleccionado de la orden de carga a realizar

################### MANTENIMIENTO INICIAL #####################


#shopt -s -o unset

################### DECLARACIONES ########################

declare -r TABLA="$1"

declare TOTAL

declare CONTADOR

declare OPERACION="$2"

declare BRUTO

declare DESCUENTO

#@@@@@@@@@@@@@@@@@@ SCRIPT ##################################	





mysql -u "${user}" --password="${pass}" --execute="SELECT repID AS ID,CONCAT(clasificacion_cla,' ',mod_md,' ',motivo_mt) AS DESCRIPCION,CANTIDAD_RE,ROUND(IF(CONDICION = CONDICION_REFERENCIA AND DESCUENTO_ESPECIAL <> '-',ROUND(ROUND(1 - DESCUENTO_ESPECIAL/100,2) * IF(UMBRAL>0 AND CANTIDAD_RE>=UMBRAL * 1000,CANTIDAD_RE * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,CANTIDAD_RE * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),IF(DESCUENTO_ESPECIFICO > '0',ROUND(ROUND(1 - DESCUENTO_ESPECIFICO/100,2) * IF(UMBRAL>0 AND CANTIDAD_RE>=UMBRAL * 1000,CANTIDAD_RE * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,CANTIDAD_RE * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),ROUND(cond_num_cd * IF(UMBRAL>0 AND CANTIDAD_RE>=UMBRAL * 1000,CANTIDAD_RE * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,CANTIDAD_RE * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2))),2) AS MONTO FROM "${DB}"."${TABLA}" JOIN("${DB}".ARTICULOS,"${DB}".PRECIOS,"${DB}".CATEGORIA,"${DB}".MODELO,"${DB}".MOTIVO,"${DB}".CLIENTE,"${DB}".OPERACIONES,"${DB}".PROOVEDOR,"${DB}".CONDICION) ON("${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".PRECIOS.RUBRO_pr="${DB}".ARTICULOS.RUBRO AND "${DB}".PRECIOS.CATEGORIA_pr="${DB}".ARTICULOS.CATEGORIA AND "${DB}".PRECIOS.MODELO_pr="${DB}".ARTICULOS.MODELO AND "${DB}".CATEGORIA.claID="${DB}".ARTICULOS.CATEGORIA AND "${DB}".MOTIVO.mtID="${DB}".ARTICULOS.MOTIVO AND "${DB}".MODELO.mdID="${DB}".ARTICULOS.MODELO AND "${DB}".ARTICULOS.artID="${DB}"."${TABLA}".ID_ARTICULO_RE AND "${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".CLIENTE.clID="${DB}".OPERACIONES.INTERESADO AND "${DB}".PROOVEDOR.pooID="${DB}".PRECIOS.PROOVEDOR) WHERE opID="${OPERACION}" ;" | column -t -s $'\t'>${temp}"tmp5.fact"



mysql -u "${user}" --password="${pass}" --execute="SELECT ROUND(IF(CONDICION = CONDICION_REFERENCIA AND DESCUENTO_ESPECIAL <> '-',ROUND(ROUND(1 - DESCUENTO_ESPECIAL/100,2) * IF(UMBRAL>0 AND CANTIDAD_RE>=UMBRAL * 1000,CANTIDAD_RE * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,CANTIDAD_RE * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),IF(DESCUENTO_ESPECIFICO > '0',ROUND(ROUND(1 - DESCUENTO_ESPECIFICO/100,2) * IF(UMBRAL>0 AND CANTIDAD_RE>=UMBRAL * 1000,CANTIDAD_RE * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,CANTIDAD_RE * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2),ROUND(cond_num_cd * IF(UMBRAL>0 AND CANTIDAD_RE>=UMBRAL * 1000,CANTIDAD_RE * CANTIDAD_MINIMA - REGALO * CANTIDAD_MINIMA,CANTIDAD_RE * CANTIDAD_MINIMA) * IF((VIGENCIA_A <= CURDATE() AND VIGENCIA_A > VIGENCIA_B) OR (VIGENCIA_A <= CURDATE() AND VIGENCIA_B > CURDATE()) OR (PRECIO_B IS NULL),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_A,PRECIO_A),IF(VALOR_AGREGADO >'0',(1 + VALOR_AGREGADO/100) * PRECIO_B,PRECIO_B)),2))),2) AS MONTO FROM "${DB}"."${TABLA}" JOIN("${DB}".ARTICULOS,"${DB}".PRECIOS,"${DB}".CATEGORIA,"${DB}".MODELO,"${DB}".MOTIVO,"${DB}".CLIENTE,"${DB}".OPERACIONES,"${DB}".PROOVEDOR,"${DB}".CONDICION) ON("${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".PRECIOS.RUBRO_pr="${DB}".ARTICULOS.RUBRO AND "${DB}".PRECIOS.CATEGORIA_pr="${DB}".ARTICULOS.CATEGORIA AND "${DB}".PRECIOS.MODELO_pr="${DB}".ARTICULOS.MODELO AND "${DB}".CATEGORIA.claID="${DB}".ARTICULOS.CATEGORIA AND "${DB}".MOTIVO.mtID="${DB}".ARTICULOS.MOTIVO AND "${DB}".MODELO.mdID="${DB}".ARTICULOS.MODELO AND "${DB}".ARTICULOS.artID="${DB}"."${TABLA}".ID_ARTICULO_RE AND "${DB}".CONDICION.cdID="${DB}".CLIENTE.CONDICION AND "${DB}".CLIENTE.clID="${DB}".OPERACIONES.INTERESADO AND "${DB}".PROOVEDOR.pooID="${DB}".PRECIOS.PROOVEDOR) WHERE opID="${OPERACION}" ;" | tail -n +2 >${temp}"tmp6.fact"



TOTAL=0
while read line_b; do
    TOTAL="$(maxima --very-quiet --batch-string "fpprintprec:7$"${TOTAL}"+"${line_b}";" | tail -n +3 | sed /^[0-9]/d | sed s/[[:blank:]]//g)"
    
done<${temp}"tmp6.fact"




echo -e "\n*  BRUTO -->  "${TOTAL}"              ">>${temp}"tmp5.fact"


cp ${temp}"tmp5.fact" ${temp}"temp2.cont"



################## MANTENIMIENTO FINAL ###################


VAR_s=${temp}"*.fact" 

rm $VAR_s

exit 192
