
### VER

SELECT * FROM SALDO_PROOVEDOR WHERE REFERENCIA=37054 OR REFERENCIA=37056;

### COPIAR saldopID

UPDATE SALDO_PROOVEDOR SET DEBE=-DEBE WHERE saldopID=273 OR saldopID=274;

### CORREGIR

UPDATE ARMADO SET CANTIDAD_ING=-CANTIDAD_ING WHERE OPERACION_REFERENCIA_AR=4348 OR OPERACION_REFERENCIA_AR=4349;
