#!/bin/bash
#
# SCRIPT PARA LA PLANIFICACION DE LAS TAREAS

###################### DECLARACIONES ####################################

declare -r CARPETA_TRABAJO=""${HOME}"/Dropbox/RODRIGO/ULTIMAS_ENTREGAS/"

declare -r nom=$(date +%d-%m-%y)"-PLANIFICACION.csv"

declare -r ARCHIVO=${CARPETA_TRABAJO}${nom}

####################### FUNCIONES ########################################

# function no_util {

# # # LEO ORDENES VIGENTES DE ENTREGA

# # mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DISTINCT (COMIENZO) FROM SOLICITUDES WHERE CLASE=9 AND COMIENZO IS NOT NULL AND REALIZACION IS NULL ORDER BY COMIENZO DESC;" | tail -n +2 | column -t -s $'\t'>${HOME}"/basura"



# # while read line ; do
    
# #     echo -e "\nORDEN DE ENTREGA ==> "${line}""
# # mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DENOMINACION FROM SOLICITUDES JOIN(OPERACIONES,CLIENTE,LOCALIDAD) ON(SOLICITUDES.REFERENCIA=OPERACIONES.opID AND OPERACIONES.INTERESADO=CLIENTE.clID AND CLIENTE.LOCALIDAD=LOCALIDAD.lcID) WHERE CLASE=9 AND REALIZACION IS NULL AND COMIENZO='${line}' ORDER BY cp_lc;" | tail -n +2 | grep -v cesar
   
    
# # done <${HOME}"/basura"

# # # LEO ORDENES VIGENTES DE ARMADO

# # mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DISTINCT (COMIENZO) FROM SOLICITUDES WHERE CLASE=6 AND COMIENZO IS NOT NULL AND REALIZACION IS NULL ORDER BY COMIENZO DESC;" | tail -n +2 | column -t -s $'\t'>${HOME}"/basura"



# # while read line ; do
    
# #     echo -e "\nORDEN DE ARMADO ==> "${line}""
# # mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DENOMINACION FROM SOLICITUDES JOIN(OPERACIONES,CLIENTE,LOCALIDAD) ON(SOLICITUDES.REFERENCIA=OPERACIONES.opID AND OPERACIONES.INTERESADO=CLIENTE.clID AND CLIENTE.LOCALIDAD=LOCALIDAD.lcID) WHERE CLASE=6 AND REALIZACION IS NULL AND COMIENZO='${line}' ORDER BY cp_lc;" | tail -n +2 | grep -v cesar
   
    
# # done <${HOME}"/basura"


# # # LEO TODAS LAS OPERACIONES PENDIENTES



# # echo "######################## ENTREGA #############################"

# # echo -e "\nORDEN DE ENTREGA ==> "
# # mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DENOMINACION FROM SOLICITUDES JOIN(OPERACIONES,CLIENTE,LOCALIDAD) ON(SOLICITUDES.REFERENCIA=OPERACIONES.opID AND OPERACIONES.INTERESADO=CLIENTE.clID AND CLIENTE.LOCALIDAD=LOCALIDAD.lcID) WHERE CLASE=9 AND REALIZACION IS NULL AND COMIENZO IS NULL AND SOLICITUD!=46 ORDER BY cp_lc;" | tail -n +2 | grep -v cesar


# # echo "######################## ARMADO #############################"

# # echo -e "\nORDEN DE ARMADO ==> "

#     # mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DENOMINACION FROM SOLICITUDES JOIN(OPERACIONES,CLIENTE,LOCALIDAD) ON(SOLICITUDES.REFERENCIA=OPERACIONES.opID AND OPERACIONES.INTERESADO=CLIENTE.clID AND CLIENTE.LOCALIDAD=LOCALIDAD.lcID) WHERE CLASE=6 AND REALIZACION IS NULL AND COMIENZO IS NULL AND SOLICITUD!=46 ORDER BY cp_lc;" | tail -n +2 | grep -v cesar
# }

function info_actual {
    
    echo -e "\n--------------------------;---------------------------" >${ARCHIVO}
       
    mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DENOMINACION AS FALTANTES,FECHA FROM SOLICITUDES JOIN(OPERACIONES,CLIENTE,LOCALIDAD) ON(SOLICITUDES.REFERENCIA=OPERACIONES.opID AND OPERACIONES.INTERESADO=CLIENTE.clID AND CLIENTE.LOCALIDAD=LOCALIDAD.lcID) WHERE CLASE=5 AND REALIZACION IS NULL AND SOLICITUD=46 ORDER BY FECHA;" | tr '\t' ';' >>${ARCHIVO} 

    echo -e "\n--------------------------;---------------------------" >>${ARCHIVO} 

    
    mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DENOMINACION AS POR_VISITAR,FECHA FROM SOLICITUDES JOIN(OPERACIONES,CLIENTE,LOCALIDAD) ON(SOLICITUDES.REFERENCIA=OPERACIONES.opID AND OPERACIONES.INTERESADO=CLIENTE.clID AND CLIENTE.LOCALIDAD=LOCALIDAD.lcID) WHERE CLASE=1 AND REALIZACION IS NULL AND COMIENZO IS NOT NULL ORDER BY FECHA,cp_lc;" | tr '\t' ';' >>${ARCHIVO}  


    echo -e "\n--------------------------;---------------------------" >>${ARCHIVO} 

    
    mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DENOMINACION AS PEDIDOS_ARMANDOSE,FECHA FROM SOLICITUDES JOIN(OPERACIONES,CLIENTE,LOCALIDAD) ON(SOLICITUDES.REFERENCIA=OPERACIONES.opID AND OPERACIONES.INTERESADO=CLIENTE.clID AND CLIENTE.LOCALIDAD=LOCALIDAD.lcID) WHERE CLASE=6 AND REALIZACION IS NULL AND COMIENZO IS NOT NULL ORDER BY FECHA,cp_lc;" | tr '\t' ';' >>${ARCHIVO}  

    echo -e "\n--------------------------;---------------------------" >>${ARCHIVO} 

    
    mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DENOMINACION AS ARMADOS,FECHA FROM SOLICITUDES JOIN(OPERACIONES,CLIENTE,LOCALIDAD) ON(SOLICITUDES.REFERENCIA=OPERACIONES.opID AND OPERACIONES.INTERESADO=CLIENTE.clID AND CLIENTE.LOCALIDAD=LOCALIDAD.lcID) WHERE CLASE=8 AND REALIZACION IS NULL AND COMIENZO IS NOT NULL ORDER BY FECHA,cp_lc;" | tr '\t' ';' >>${ARCHIVO}   

    echo -e "\n--------------------------;---------------------------" >>${ARCHIVO} 

   
    mysql -u ${user} --password=${pass} --execute="USE "${DB}";SELECT DENOMINACION AS PENDIENTES,FECHA FROM SOLICITUDES JOIN(OPERACIONES,CLIENTE,LOCALIDAD) ON(SOLICITUDES.REFERENCIA=OPERACIONES.opID AND OPERACIONES.INTERESADO=CLIENTE.clID AND CLIENTE.LOCALIDAD=LOCALIDAD.lcID) LEFT JOIN SOLICITUDES t2 ON (t2.REFERENCIA=SOLICITUDES.REFERENCIA AND t2.CLASE=6 AND t2.REALIZACION IS NULL AND t2.COMIENZO IS NOT NULL) LEFT JOIN SOLICITUDES t3 ON (t3.REFERENCIA=SOLICITUDES.REFERENCIA AND t3.CLASE=8 AND t3.REALIZACION IS NULL AND t3.COMIENZO IS NOT NULL) LEFT JOIN SOLICITUDES t4 ON (t4.REFERENCIA=SOLICITUDES.REFERENCIA AND t4.CLASE=1 AND t4.REALIZACION IS NULL AND t4.COMIENZO IS NOT NULL) WHERE t2.CLASE IS NULL AND t4.CLASE IS NULL AND t3.CLASE IS NULL AND SOLICITUDES.CLASE=9 AND SOLICITUDES.REALIZACION IS NULL AND SOLICITUD!=46 ORDER BY FECHA,cp_lc;" | tr '\t' ';' >>${ARCHIVO}  

}


########################## SCRIPT PRINCIPAL ###########################################


info_actual && dialog --msgbox """SE ENCUENTRA EN LA CARPETA DE DROPBOX EL ARCHIVO "${nom}"""" 0 0




########################## MANTENIMIENTO ###############################################    

exit 192
