USE MIDOKA_PGC_B;
SELECT SOLICITUDES.REALIZACION AS FECHA, DENOMINACION AS 'CLIENTE',opID AS 'REMITO',nombre_rhd AS 'VENDEDOR',MONTO
   FROM COMISIONES JOIN(OPERACIONES,SOLICITUDES,CLIENTE,RECURSOS_HUMANOS_DISPONIBLES) ON(opID=OPERACION_REF_C
   	AND opID=SOLICITUDES.REFERENCIA AND clID=INTERESADO AND TRABAJADOR=rhdID)
   WHERE ((VIGENCIA IS NULL
          AND CANCELACION IS NULL)
     OR (VIGENCIA IS NULL
         AND CANCELACION IS NOT NULL))
	AND CLASE=9 AND REALIZACION>'Linf' AND REALIZACION<='Lsup' ORDER BY FECHA,REMITO;
