USE MIDOKA_PGC_B;
SELECT t4.FECHA AS 'FECHA',
       ROUND(t1.STOCK, 0) AS 'Stock',
       ROUND(t5.armadosFacturados, 0) AS '5armadofacturados',
       ROUND(IFNULL(t6.armados,0), 0) AS 'armados',
       ROUND(t1.STOCK+IFNULL(t6.armados,0)+t5.armadosFacturados, 0) AS 'Suma'
FROM
  (SELECT 'ACTUAL' AS ACTUAL,
          SUM((IFNULL(CANTIDAD_CST, 0) + IFNULL(CANTIDAD_ING, 0) + IFNULL(CANTIDAD_DEVOL, 0) - IFNULL(CANTIDAD_EGR, 0)) * CANTIDAD_MINIMA * IF(IFNULL(PRECIO_A, 0) > IFNULL(PRECIO_B, 0), IFNULL(PRECIO_A, 0) * (1 - (DESCUENTO / 100)), IFNULL(PRECIO_B, 0) * (1 - (DESCUENTO / 100)))) AS 'STOCK'
   FROM ARMADO
   JOIN (OPERACIONES,
         RUBRO,
         CATEGORIA,
         MODELO,
         MOTIVO,
         PROOVEDOR,
         PRECIOS,
         ARTICULOS) ON (opID=OPERACION_REFERENCIA_AR
                        AND RUBRO.ruID=PRECIOS.RUBRO_pr
                        AND CATEGORIA.claID=PRECIOS.CATEGORIA_pr
                        AND MODELO.mdID=PRECIOS.MODELO_pr
                        AND PROOVEDOR.pooID=PRECIOS.PROOVEDOR
                        AND ARTICULOS.RUBRO=PRECIOS.RUBRO_pr
                        AND ARTICULOS.CATEGORIA=PRECIOS.CATEGORIA_pr
                        AND ARTICULOS.MODELO=PRECIOS.MODELO_pr
                        AND ARTICULOS.artID=ARMADO.ID_ARTICULO_AR
                        AND ARTICULOS.MOTIVO=MOTIVO.mtID)
   WHERE OPERACIONES.FECHA<='2019-12-31') t1
JOIN
  (SELECT 'ACTUAL' AS ACTUAL,
          SUM(-CANTIDAD_AR) * CANTIDAD_MINIMA * IF(IFNULL(PRECIO_A, 0) > IFNULL(PRECIO_B, 0), IFNULL(PRECIO_A, 0) * (1 - (DESCUENTO / 100)), IFNULL(PRECIO_B, 0) * (1 - (DESCUENTO / 100))) AS 'armadosFacturados'
   FROM ARMADO
   JOIN (OPERACIONES,
         RUBRO,
         CATEGORIA,
         MODELO,
         MOTIVO,
         PROOVEDOR,
         PRECIOS,
         ARTICULOS,
	 SOLICITUDES) ON (opID=OPERACION_REFERENCIA_AR
                        AND RUBRO.ruID=PRECIOS.RUBRO_pr
                        AND CATEGORIA.claID=PRECIOS.CATEGORIA_pr
                        AND MODELO.mdID=PRECIOS.MODELO_pr
                        AND PROOVEDOR.pooID=PRECIOS.PROOVEDOR
                        AND ARTICULOS.RUBRO=PRECIOS.RUBRO_pr
                        AND ARTICULOS.CATEGORIA=PRECIOS.CATEGORIA_pr
                        AND ARTICULOS.MODELO=PRECIOS.MODELO_pr
                        AND ARTICULOS.artID=ARMADO.ID_ARTICULO_AR
                        AND ARTICULOS.MOTIVO=MOTIVO.mtID AND opID=SOLICITUDES.REFERENCIA)
   WHERE SOLICITUDES.REALIZACION<='2019-12-31' AND CLASE=9) t5 JOIN
  (SELECT 'ACTUAL' AS ACTUAL,
          SUM(CANTIDAD_AR * CANTIDAD_MINIMA * IF(IFNULL(PRECIO_A, 0) > IFNULL(PRECIO_B, 0), IFNULL(PRECIO_A, 0) * (1 - (DESCUENTO / 100)), IFNULL(PRECIO_B, 0) * (1 - (DESCUENTO / 100)))) AS 'armados'
   FROM ARMADO
   JOIN (OPERACIONES,
         RUBRO,
         CATEGORIA,
         MODELO,
         MOTIVO,
         PROOVEDOR,
         PRECIOS,
         ARTICULOS,
	 SOLICITUDES) ON (opID=OPERACION_REFERENCIA_AR
                        AND RUBRO.ruID=PRECIOS.RUBRO_pr
                        AND CATEGORIA.claID=PRECIOS.CATEGORIA_pr
                        AND MODELO.mdID=PRECIOS.MODELO_pr
                        AND PROOVEDOR.pooID=PRECIOS.PROOVEDOR
                        AND ARTICULOS.RUBRO=PRECIOS.RUBRO_pr
                        AND ARTICULOS.CATEGORIA=PRECIOS.CATEGORIA_pr
                        AND ARTICULOS.MODELO=PRECIOS.MODELO_pr
                        AND ARTICULOS.artID=ARMADO.ID_ARTICULO_AR
                        AND ARTICULOS.MOTIVO=MOTIVO.mtID AND opID=SOLICITUDES.REFERENCIA)
   WHERE (SOLICITUDES.COMIENZO<='2019-12-31' AND SOLICITUDES.REALIZACION IS NULL AND CLASE=8) OR (SOLICITUDES.COMIENZO<='2019-12-31' AND SOLICITUDES.REALIZACION IS NULL AND CLASE=9)) t6   
JOIN
  (SELECT 'ACTUAL' AS ACTUAL, SUM(IFNULL(DEBE, 0) - IFNULL(HABER, 0) - IFNULL(DEVOLUCION, 0) - IFNULL(PERDIDAS, 0)) AS 'CLIENTES'
   FROM CUENTA_CORRIENTE
   JOIN (OPERACIONES) ON(opID=OPERACION_REF_CC)
   WHERE OPERACIONES.FECHA<='2019-12-31') t2 ON(t1.ACTUAL=t2.ACTUAL)
JOIN
  (SELECT 'ACTUAL' AS ACTUAL, SUM(IFNULL(DEBE, 0) - IFNULL(HABER, 0)) AS 'PROVEEDOR'
   FROM SALDO_PROOVEDOR JOIN(OPERACIONES) ON(OPERACION_ASOCIADA=opID)
   WHERE OPERACIONES.FECHA<='2019-12-31') t3 ON(t1.ACTUAL=t3.ACTUAL)
JOIN
  (SELECT 'ACTUAL' AS ACTUAL,
          REGISTRO AS 'CAJA',
          FECHA
   FROM CONTABLES
   WHERE TIPO_REGISTRO=5
     AND FECHA='2019-12-31') t4 ON(t1.ACTUAL=t4.ACTUAL);

